### ISSUE TITLE
[Enh] Geopackage import

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/spatialdata#21]
[4420c24f4fa65](https://github.com/openmole/spatialdata/commit/4420c24f4fa65ced3d3622b4606fa006d432f412) implements geometry features import from GeoPackage format (https://www.geopackage.org/)
- used the geopackage-java library (https://github.com/ngageoint/geopackage-java) for this; it may be better to use the geotools geopackage plugin (https://mvnrepository.com/artifact/org.geotools/gt-geopkg/22.2) to avoid cumbersome conversions between geometries, but not sure which one is better in terms of performance.
@julienperret what would you suggest?

**Comment by julienperret** [comment]
I never used the geopackage-java library so I can't be entirely sure.
We still have some gt code so using gt-geopkg might be the simplest way to go.

**Comment by JusteRaimbault** [comment]
Ok I went with that (implemented in [321ab10](https://github.com/openmole/spatialdata/commit/321ab104ad698d8841868509abe1771a1b9835b5) ) - the gt-geopkg is smaller but called several dependencies so it may be larger in terms of bundle size in the end but anyway
